# Generated by Django 4.2 on 2024-05-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Catalog_Management', '0010_alter_products_product_image'),
        ('Customer_Management', '0001_initial'),
        ('Transaction_Processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction_processing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction_processing',
            name='customer_phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customer_Management.customer_info'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction_processing',
            unique_together={('barcode_t', 'customer_phone')},
        ),
        migrations.RemoveField(
            model_name='transaction_processing',
            name='customer_t',
        ),
    ]
