# Generated by Django 4.2 on 2024-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Processing', '0002_alter_transaction_processing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_processing',
            name='customer_phone',
            field=models.CharField(default='waiting', max_length=15),
        ),
    ]
