# Generated by Django 4.2 on 2024-05-25 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Processing', '0003_alter_transaction_processing_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_processing',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
