# Generated by Django 4.2 on 2024-05-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Processing', '0005_alter_transaction_processing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction_processing',
            unique_together=set(),
        ),
    ]
