# Generated by Django 4.2 on 2024-05-26 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_management', '0051_alter_employee_account_activation_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_account',
            name='activation_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 1, 8, 54, 985646, tzinfo=datetime.timezone.utc)),
        ),
    ]
