# Generated by Django 4.2 on 2024-05-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Catalog_Management', '0002_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
