# Generated by Django 4.2 on 2024-05-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Catalog_Management', '0004_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='home/images/products/'),
        ),
    ]
