# Generated by Django 4.2 on 2024-05-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Catalog_Management', '0007_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='product_image',
        ),
    ]
